name: Update cards
on:
  schedule:
    - cron: '0 1 * * *' # Check daily for hearthstone card updates
  workflow_dispatch:
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install -r .github/workflows/requirements.txt # Will automatically pull the latest version (and thus card data) from pypi
    - run: python -u .github/workflows/update_cards.py
      timeout-minutes: 60
    - name: Commit card updates (if any)
      run: |
        NUM_FILES=0
        git diff --quiet --exit-code || NUM_FILES=$?
        echo "Detected $NUM_FILES changed files"
        if [ $NUM_FILES -eq 0 ]; then exit 0; fi # If no unstaged files, exit the script
        git config --global user.email "cardle@noreply.github.com"
        git config --global user.name "Cardle crontab"
        git commit -am "Updated cards on $(date)"
        git push
